version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres:
    driver: local
